// src/components/DraggableCube.vue
<template>
    <div ref="canvasContainer" class="canvas-container"></div>
</template>
  
  <script>
import * as THREE from "three";

export default {
  name: "DraggableCube",
  mounted() {
    this.initThree();
  },
  methods: {
    initThree() {
      const container = this.$refs.canvasContainer;

      // 设置场景
      const scene = new THREE.Scene();
      scene.background = new THREE.Color(0xeeeeee);

      // 设置相机
      const camera = new THREE.PerspectiveCamera(
        75,
        container.clientWidth / container.clientHeight,
        0.1,
        1000
      );
      camera.position.z = 5;

      // 设置渲染器
      const renderer = new THREE.WebGLRenderer({ antialias: true });
      renderer.setSize(container.clientWidth, container.clientHeight);
      container.appendChild(renderer.domElement);

      // 添加立方体
      const geometry = new THREE.BoxGeometry(3, 3, 3);
      //   const material = new THREE.MeshStandardMaterial({ color: 0x007bff });
      // 创建材质数组，每个面一个材质
      const materials = [
        new THREE.MeshBasicMaterial({ color: 0xffffff }), // 白色
        new THREE.MeshBasicMaterial({ color: 0xffff00 }), // 黄色
        new THREE.MeshBasicMaterial({ color: 0xff0000 }), // 红色
        new THREE.MeshBasicMaterial({ color: 0xffa500 }), // 橙色
        new THREE.MeshBasicMaterial({ color: 0x00ff00 }), // 绿色
        new THREE.MeshBasicMaterial({ color: 0x0000ff })  // 蓝色
      ];
      const cube = new THREE.Mesh(geometry, materials);

      // 设置立方体的旋转角度，以便从一个角落看到它
      cube.rotation.x = Math.PI / 6; // 30度沿x轴旋转
      cube.rotation.y = Math.PI / 4; // 45度沿y轴旋转
      scene.add(cube);

      // 添加光源
      const light = new THREE.DirectionalLight(0xffffff, 1);
      light.position.set(10, 10, 10);
      scene.add(light);

      // 添加鼠标拖动控制
      let isDragging = false;
      let previousMousePosition = { x: 0, y: 0 };

      container.addEventListener("mousedown", (event) => {
        isDragging = true;
      });

      container.addEventListener("mousemove", (event) => {
        if (isDragging) {
          const deltaMove = {
            x: event.offsetX - previousMousePosition.x,
            y: event.offsetY - previousMousePosition.y,
          };

          const rotationSpeed = 0.01;
          cube.rotation.y += deltaMove.x * rotationSpeed;
          cube.rotation.x += deltaMove.y * rotationSpeed;
        }

        previousMousePosition = {
          x: event.offsetX,
          y: event.offsetY,
        };
      });

      container.addEventListener("mouseup", () => {
        isDragging = false;
      });

      container.addEventListener("mouseleave", () => {
        isDragging = false;
      });

      // 动画循环
      const animate = () => {
        requestAnimationFrame(animate);
        renderer.render(scene, camera);
      };
      animate();
    },
  },
};
  </script>
  
  <style scoped>
.canvas-container {
    width: 100%;
    height: 100vh;
    overflow: hidden;
}
</style>

// src/components/DraggableCube.tsx
import React, { useEffect, useRef } from 'react';
import * as THREE from 'three';
import { Pane } from 'tweakpane';
import anime from 'animejs';

const DraggableCube: React.FC = () => {
  const containerRef = useRef<HTMLDivElement>(null);
  const sceneRef = useRef<THREE.Scene>();
  const cameraRef = useRef<THREE.PerspectiveCamera>();
  const rendererRef = useRef<THREE.WebGLRenderer>();
  const cubeRef = useRef<THREE.Group>();
  const isDraggingRef = useRef(false);
  const previousMousePositionRef = useRef({ x: 0, y: 0 });

  useEffect(() => {
    if (!containerRef.current) return;

    // 初始化场景
    sceneRef.current = new THREE.Scene();
    cameraRef.current = new THREE.PerspectiveCamera(
      75,
      window.innerWidth / window.innerHeight,
      0.1,
      1000
    );
    rendererRef.current = new THREE.WebGLRenderer({ antialias: true });

    const scene = sceneRef.current;
    const camera = cameraRef.current;
    const renderer = rendererRef.current;

    renderer.setSize(window.innerWidth, window.innerHeight);
    containerRef.current.appendChild(renderer.domElement);

    // 创建魔方
    cubeRef.current = createRubiksCube();
    scene.add(cubeRef.current);

    // 设置相机位置
    camera.position.z = 5;

    // 添加灯光
    const ambientLight = new THREE.AmbientLight(0xffffff, 0.5);
    scene.add(ambientLight);

    const directionalLight = new THREE.DirectionalLight(0xffffff, 0.5);
    directionalLight.position.set(10, 10, 10);
    scene.add(directionalLight);

    // 动画循环
    const animate = () => {
      requestAnimationFrame(animate);
      renderer.render(scene, camera);
    };
    animate();

    // 事件监听器
    const handleMouseDown = (event: MouseEvent) => {
      isDraggingRef.current = true;
      previousMousePositionRef.current = {
        x: event.clientX,
        y: event.clientY
      };
    };

    const handleMouseMove = (event: MouseEvent) => {
      if (!isDraggingRef.current || !cubeRef.current) return;

      const deltaMove = {
        x: event.clientX - previousMousePositionRef.current.x,
        y: event.clientY - previousMousePositionRef.current.y
      };

      cubeRef.current.rotation.y += deltaMove.x * 0.01;
      cubeRef.current.rotation.x += deltaMove.y * 0.01;

      previousMousePositionRef.current = {
        x: event.clientX,
        y: event.clientY
      };
    };

    const handleMouseUp = () => {
      isDraggingRef.current = false;
    };

    renderer.domElement.addEventListener('mousedown', handleMouseDown);
    renderer.domElement.addEventListener('mousemove', handleMouseMove);
    renderer.domElement.addEventListener('mouseup', handleMouseUp);

    // 清理函数
    return () => {
      renderer.domElement.removeEventListener('mousedown', handleMouseDown);
      renderer.domElement.removeEventListener('mousemove', handleMouseMove);
      renderer.domElement.removeEventListener('mouseup', handleMouseUp);
      containerRef.current?.removeChild(renderer.domElement);
    };
  }, []);

  return <div ref={containerRef} style={{ width: '100%', height: '100vh' }} />;
};

// 创建魔方的辅助函数
function createRubiksCube() {
  const cubeGroup = new THREE.Group();
  const size = 1;
  const gap = 0.1;

  for (let x = -1; x <= 1; x++) {
    for (let y = -1; y <= 1; y++) {
      for (let z = -1; z <= 1; z++) {
        const geometry = new THREE.BoxGeometry(size, size, size);
        const materials = [
          new THREE.MeshPhongMaterial({ color: 0xff0000 }), // 右
          new THREE.MeshPhongMaterial({ color: 0xff8c00 }), // 左
          new THREE.MeshPhongMaterial({ color: 0xffff00 }), // 上
          new THREE.MeshPhongMaterial({ color: 0xffffff }), // 下
          new THREE.MeshPhongMaterial({ color: 0x0000ff }), // 前
          new THREE.MeshPhongMaterial({ color: 0x00ff00 })  // 后
        ];

        const cube = new THREE.Mesh(geometry, materials);
        cube.position.set(
          x * (size + gap),
          y * (size + gap),
          z * (size + gap)
        );

        cubeGroup.add(cube);
      }
    }
  }

  return cubeGroup;
}

export default DraggableCube;
